project_id = "msbmyiqhohtjdfbjmxlf"

[functions.activate-free-plan]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = true

[functions.increment-coupon-usage]
verify_jwt = true

[functions.cleanup-old-data]
verify_jwt = false

[functions.create-razorpay-payment]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true

[functions.generate-invoice]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.generate-sample-voice]
verify_jwt = true

[functions.generate-voice]
verify_jwt = true

[functions.generate-prebuilt-voice]
verify_jwt = false

[functions.purge-expired-history]
verify_jwt = false

[functions.purge-user-analytics]
verify_jwt = false

[functions.translate-text]
verify_jwt = true

[functions.improve-grammar]
verify_jwt = true

[functions.send-email-confirmation]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.confirm-email]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.convert-audio]
verify_jwt = true

[functions.issue-audio-token]
verify_jwt = true

[functions.stream-audio]
verify_jwt = true

[functions.signup]
verify_jwt = false
